### ISSUE TITLE
Linting Tools

### ISSUE THREAD

**Issue by ChristianLuxem** [jraddatz99/jraddatz.de#2]
Hallo Jasper,

schaue dir mal das gulp-eslint plugin an und lasse dein JavaScript durch ESLint laufen. Als Basis für die Configuration von Eslint solltest du dir airBnB anschauen, deren Regeln sind sehr bekannt und "Best Practice". 
Ansonsten gute Arbeit!

**Comment by jraddatz99** [comment]
Danke für den Tipp! Das schaue ich mir gerne mal genauer an.
